
const LANG = 'zh_CN'

const HOST = {
    BASE: 'wx2.qq.com',
    WECHAT: 'weixin.qq.com',
    FILE: 'file.wx.qq.com',
    PUSH: [
        'webpush.weixin.qq.com',
        'webpush.wx2.qq.com',
        'webpush.wx8.qq.com',
        'webpush.weixin.qq.com',
        'webpush.web2.wechat.com',
        'webpush.web.wechat.com',
    ],
}

const QRCODE_PATH = 'https://login.weixin.qq.com/qrcode/'

const GET_API = (BASE = HOST.BASE, WECHAT = HOST.WECHAT, FILE = HOST.FILE, PUSH = HOST.PUSH[0]) => ({
    JSlOGIN: 'https://login.' + WECHAT + '/jslogin',
    LOGIN: 'https://login.' + WECHAT + '/cgi-bin/mmwebwx-bin/login',
    SYNCCHECK: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/synccheck',
    WEBWXDOWNLOADMEDIA: 'https://' + FILE + '/cgi-bin/mmwebwx-bin/webwxgetmedia',
    WEBWXUPLOADMEDIA: 'https://' + FILE + '/cgi-bin/mmwebwx-bin/webwxuploadmedia',
    WEBWXPREVIEW: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxpreview',
    WEBWXINIT: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxinit',
    WEBWXGETCONTACT: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxgetcontact',
    WEBWXSYNC: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxsync',
    WEBWXBATCHGETCONTACT: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxbatchgetcontact',
    WEBWXGETICON: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxgeticon',
    WEBWXSENDMSG: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxsendmsg',
    WEBWXSENDMSGIMG: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxsendmsgimg',
    WEBWXSENDEMOTICON: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxsendemoticon',
    WEBWXSENDAPPMSG: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxsendappmsg',
    WEBWXGETHEADIMG: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxgetheadimg',
    WEBWXGETMSGIMG: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxgetmsgimg',
    WEBWXGETMEDIA: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxgetmedia',
    WEBWXGETVIDEO: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxgetvideo',
    WEBWXLOGOUT: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxlogout',
    WEBWXGETVOICE: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxgetvoice',
    WEBWXUPDATECHATROOM: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxupdatechatroom',
    WEBWXCREATECHATROOM: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxcreatechatroom',
    WEBWXSTATUSNOTIFY: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxstatusnotify',
    WEBWXCHECKURL: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxcheckurl',
    WEBWXVERIFYUSER: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxverifyuser',
    WEBWXFEEDBACK: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxsendfeedback',
    WEBWXREPORT: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxstatreport',
    WEBWXSEARCH: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxsearchcontact',
    WEBWXOPLOG: 'https://' + BASE + '/cgi-bin/mmwebwx-bin/webwxoplog'
})

const CODES = {
  OPLOG_CMD_ID: {
    TOPCONTACT: 3,
    MODREMARKNAME: 2,
  },
  SP_CONTACT_FILE_HELPER: 'filehelper',
  SP_CONTACT_NEWSAPP: 'newsapp',
  SP_CONTACT_RECOMMEND_HELPER: 'fmessage',
  CONTACTFLAG_CONTACT: 1,
  CONTACTFLAG_CHATCONTACT: 2,
  CONTACTFLAG_CHATROOMCONTACT: 4,
  CONTACTFLAG_BLACKLISTCONTACT: 8,
  CONTACTFLAG_DOMAINCONTACT: 16,
  CONTACTFLAG_HIDECONTACT: 32,
  CONTACTFLAG_FAVOURCONTACT: 64,
  CONTACTFLAG_3RDAPPCONTACT: 128,
  CONTACTFLAG_SNSBLACKLISTCONTACT: 256,
  CONTACTFLAG_NOTIFYCLOSECONTACT: 512,
  CONTACTFLAG_TOPCONTACT: 2048,
  MM_USERATTRVERIFYFALG_BIZ: 1,
  MM_USERATTRVERIFYFALG_FAMOUS: 2,
  MM_USERATTRVERIFYFALG_BIZ_BIG: 4,
  MM_USERATTRVERIFYFALG_BIZ_BRAND: 8,
  MM_USERATTRVERIFYFALG_BIZ_VERIFIED: 16,
  MM_DATA_TEXT: 1,
  MM_DATA_HTML: 2,
  MM_DATA_IMG: 3,
  MM_DATA_PRIVATEMSG_TEXT: 11,
  MM_DATA_PRIVATEMSG_HTML: 12,
  MM_DATA_PRIVATEMSG_IMG: 13,
  MM_DATA_VOICEMSG: 34,
  MM_DATA_PUSHMAIL: 35,
  MM_DATA_QMSG: 36,
  MM_DATA_VERIFYMSG: 37,
  MM_DATA_PUSHSYSTEMMSG: 38,
  MM_DATA_QQLIXIANMSG_IMG: 39,
  MM_DATA_POSSIBLEFRIEND_MSG: 40,
  MM_DATA_SHARECARD: 42,
  MM_DATA_VIDEO: 43,
  MM_DATA_VIDEO_IPHONE_EXPORT: 44,
  MM_DATA_EMOJI: 47,
  MM_DATA_LOCATION: 48,
  MM_DATA_APPMSG: 49,
  MM_DATA_VOIPMSG: 50,
  MM_DATA_STATUSNOTIFY: 51,
  MM_DATA_VOIPNOTIFY: 52,
  MM_DATA_VOIPINVITE: 53,
  MM_DATA_MICROVIDEO: 62,
  MM_DATA_SYSNOTICE: 9999,
  MM_DATA_SYS: 1e4,
  MM_DATA_RECALLED: 10002,
  MSGTYPE_TEXT: 1,
  MSGTYPE_IMAGE: 3,
  MSGTYPE_VOICE: 34,
  MSGTYPE_VIDEO: 43,
  MSGTYPE_MICROVIDEO: 62,
  MSGTYPE_EMOTICON: 47,
  MSGTYPE_APP: 49,
  MSGTYPE_VOIPMSG: 50,
  MSGTYPE_VOIPNOTIFY: 52,
  MSGTYPE_VOIPINVITE: 53,
  MSGTYPE_LOCATION: 48,
  MSGTYPE_STATUSNOTIFY: 51,
  MSGTYPE_SYSNOTICE: 9999,
  MSGTYPE_POSSIBLEFRIEND_MSG: 40,
  MSGTYPE_VERIFYMSG: 37,
  MSGTYPE_SHARECARD: 42,
  MSGTYPE_SYS: 1e4,
  MSGTYPE_RECALLED: 10002,
  MSG_SEND_STATUS_READY: 0,
  MSG_SEND_STATUS_SENDING: 1,
  MSG_SEND_STATUS_SUCC: 2,
  MSG_SEND_STATUS_FAIL: 5,
  APPMSGTYPE_TEXT: 1,
  APPMSGTYPE_IMG: 2,
  APPMSGTYPE_AUDIO: 3,
  APPMSGTYPE_VIDEO: 4,
  APPMSGTYPE_URL: 5,
  APPMSGTYPE_ATTACH: 6,
  APPMSGTYPE_OPEN: 7,
  APPMSGTYPE_EMOJI: 8,
  APPMSGTYPE_VOICE_REMIND: 9,
  APPMSGTYPE_SCAN_GOOD: 10,
  APPMSGTYPE_GOOD: 13,
  APPMSGTYPE_EMOTION: 15,
  APPMSGTYPE_CARD_TICKET: 16,
  APPMSGTYPE_REALTIME_SHARE_LOCATION: 17,
  APPMSGTYPE_TRANSFERS: 2e3,
  APPMSGTYPE_RED_ENVELOPES: 2001,
  APPMSGTYPE_READER_TYPE: 100001,
  UPLOAD_MEDIA_TYPE_IMAGE: 1,
  UPLOAD_MEDIA_TYPE_VIDEO: 2,
  UPLOAD_MEDIA_TYPE_AUDIO: 3,
  UPLOAD_MEDIA_TYPE_ATTACHMENT: 4,
  PROFILE_BITFLAG_NOCHANGE: 0,
  PROFILE_BITFLAG_CHANGE: 190,
  CHATROOM_NOTIFY_OPEN: 1,
  CHATROOM_NOTIFY_CLOSE: 0,
  STATUS_NOTIFY_CODE_READED: 1,
  STATUS_NOTIFY_CODE_ENTER_SESSION: 2,
  STATUS_NOTIFY_CODE_INITED: 3,
  STATUS_NOTIFY_CODE_SYNC_CONV: 4,
  STATUS_NOTIFY_CODE_QUIT_SESSION: 5,
  VERIFYUSER_OPCODE_ADDCONTACT: 1,
  VERIFYUSER_OPCODE_SENDREQUEST: 2,
  VERIFYUSER_OPCODE_VERIFYOK: 3,
  VERIFYUSER_OPCODE_VERIFYREJECT: 4,
  VERIFYUSER_OPCODE_SENDERREPLY: 5,
  VERIFYUSER_OPCODE_RECVERREPLY: 6,
  ADDSCENE_PF_QQ: 4,
  ADDSCENE_PF_EMAIL: 5,
  ADDSCENE_PF_CONTACT: 6,
  ADDSCENE_PF_WEIXIN: 7,
  ADDSCENE_PF_GROUP: 8,
  ADDSCENE_PF_UNKNOWN: 9,
  ADDSCENE_PF_MOBILE: 10,
  ADDSCENE_PF_WEB: 33,
  TIMEOUT_SYNC_CHECK: 0,
  EMOJI_FLAG_GIF: 2,
  KEYCODE_BACKSPACE: 8,
  KEYCODE_ENTER: 13,
  KEYCODE_SHIFT: 16,
  KEYCODE_ESC: 27,
  KEYCODE_DELETE: 34,
  KEYCODE_ARROW_LEFT: 37,
  KEYCODE_ARROW_UP: 38,
  KEYCODE_ARROW_RIGHT: 39,
  KEYCODE_ARROW_DOWN: 40,
  KEYCODE_NUM2: 50,
  KEYCODE_AT: 64,
  KEYCODE_NUM_ADD: 107,
  KEYCODE_NUM_MINUS: 109,
  KEYCODE_ADD: 187,
  KEYCODE_MINUS: 189,
  MM_NOTIFY_CLOSE: 0,
  MM_NOTIFY_OPEN: 1,
  MM_SOUND_CLOSE: 0,
  MM_SOUND_OPEN: 1,
  MM_SEND_FILE_STATUS_QUEUED: 0,
  MM_SEND_FILE_STATUS_SENDING: 1,
  MM_SEND_FILE_STATUS_SUCCESS: 2,
  MM_SEND_FILE_STATUS_FAIL: 3,
  MM_SEND_FILE_STATUS_CANCEL: 4,
  MM_EMOTICON_WEB: '_web',
}

const SP_ACCOUNTS = 'newsapp,fmessage,filehelper,weibo,qqmail,fmessage,' +
  'tmessage,qmessage,qqsync,floatbottle,lbsapp,shakeapp,medianote,qqfriend,' +
  'readerapp,blogapp,facebookapp,masssendapp,meishiapp,feedsapp,voip,' +
  'blogappweixin,weixin,brandsessionholder,weixinreminder,wxid_novlwrv3lqwv11,' +
  'gh_22b87fa7cb3c,officialaccounts,notification_messages,wxid_novlwrv3lqwv11,' +
  'gh_22b87fa7cb3c,wxitil,userexperience_alarm,notification_messages'

module.exports = { 
    LANG, 
    HOST, 
    QRCODE_PATH,
    GET_API, 
    CODES,
    SP_ACCOUNTS
}